{
    "product": "CreditSoft Intranet",
    "channel": "stable",
    "latest_version": "2026.4.21.38",
    "latest_build": "2026.04.21.183735",
    "published_at": "2026-04-21T18:48:06+00:00",
    "headline": "CreditSoft 2026.4.21.38 is ready",
    "summary": "Date-based release publishing and client roster alignment.",
    "notes": [
        "CreditSoft 2026.4.21.38 moves the roster stage links back to the right of search and tightens the client table width.",
        "CreditSoft 2026.4.21.38 adds date-based release versions using YYYY.M.D.N for update packages and feed publishing.",
        "Browser companion 0.5.10 switches active report pulls and DisputeFox imports into a focused processing screen with the extra buttons hidden and a compact stop control left visible.",
        "CreditSoft 0.9.37 forwards imported DisputeFox admin invoices and client profile Billing rows to www.creditsoft.app under the saved office license code.",
        "CreditSoft 0.9.37 keeps the browser companion free of public write secrets: the companion sends to the intranet, then the office server queues and posts the public billing-intelligence packet.",
        "CreditSoft 0.9.37 strips password, SSN, token, secret, and security-answer fields before public billing intelligence is stored for old-platform spend analysis.",
        "CreditSoft 0.9.36 ships browser companion 0.5.9 with the unused DisputeFox login form removed from the popup and side panel import lanes.",
        "CreditSoft 0.9.36 keeps Import client profiles on client/profile pages and stops that pass from opening the admin billing_report.jsp invoice report automatically.",
        "CreditSoft 0.9.36 labels the invoice lane as Admin invoices so client Billing/profile history stays distinct from admin invoice reports.",
        "CreditSoft 0.9.35 ships browser companion 0.5.8 with DisputeFox profile-history preservation for Billing, Messages, Scores, Tasks, Letters, Disputes, and related migration pages.",
        "CreditSoft 0.9.35 normalizes DisputeFox profile Billing rows into client payment history while also staging the raw rows for migration audit review.",
        "CreditSoft 0.9.35 keeps static freeze-address lookup tables out of migrated history so real client activity is not mixed with template data.",
        "CreditSoft 0.9.34 ships browser companion 0.5.7 with Documents & POA row capture that prefers real DisputeFox download files before preview images.",
        "CreditSoft 0.9.34 raises DisputeFox document import from 25 to 80 files per profile pass so larger client folders are not cut short.",
        "CreditSoft 0.9.34 keeps stored document source values, fallback filenames, and upload categories on DisputeFox/client_documents language instead of Pulse labels.",
        "CreditSoft 0.9.33 renames the left rail Meta item to Social while keeping the social calendar route intact.",
        "CreditSoft 0.9.33 keeps the Meta brand mark for the Social lane so the icon still represents the connected Meta workspace.",
        "CreditSoft 0.9.32 renames the left rail Violations item to Compliance while keeping the existing /violations route intact.",
        "CreditSoft 0.9.32 updates the client workspace tab and footer quick link to say Compliance.",
        "CreditSoft 0.9.31 keeps Clients & Intake visible in the Workspace rail after the rename.",
        "CreditSoft 0.9.31 renames the left rail Clients item to Clients & Intake.",
        "CreditSoft 0.9.31 groups the client flyout into Clients, Leads, Lifecycle, Records, and Tools.",
        "CreditSoft 0.9.31 uses the Font Awesome fire icon for the Fired lifecycle lane and widens the flyout for better scanning.",
        "CreditSoft 0.9.30 shows the client health header on Notes, Letters, Briefs, Audit, and Compare pages.",
        "CreditSoft 0.9.30 sends clients with no imported reporting cycle back to the profile instead of showing a 404 on Compare.",
        "CreditSoft 0.9.30 includes the roster search/link alignment and narrower Person column fixes from 0.9.29.",
        "CreditSoft 0.9.29 fixes client profile pages that could throw a server error when checking document access.",
        "CreditSoft 0.9.29 moves the Clients, Leads, Terminated, Fired, Canceled, Graduated, and All roster links back to the right of search.",
        "CreditSoft 0.9.29 narrows the Person column and table width slightly to reduce horizontal scrolling on the clients roster.",
        "CreditSoft 0.9.28 tightens the left icon rail by reducing vertical item spacing and shorter rail hit areas.",
        "CreditSoft 0.9.28 adds a divider above the Info utility icon so Workspace, Operations, and Utilities read as three rail sections.",
        "CreditSoft 0.9.27 routes /install/intranet-client to the public updates.creditsoft.app package instead of generating office-specific zips.",
        "CreditSoft 0.9.27 makes the employee intranet client installer probe port 80 first when available, then 8877 and the next free local ports.",
        "CreditSoft 0.9.27 makes server-node installs prefer host port 80 for the office app when it is free, then fall back to 8001+.",
        "CreditSoft 0.9.27 adds explicit bind-IP support for server nodes so a router/DHCP-reserved LAN address can be used without hardcoding one into the package.",
        "CreditSoft 0.9.27 adds a business-profile-aware offline PWA landing page with bookmark guidance when the local router is up but the office node is not reachable.",
        "CreditSoft 0.9.26 adds a separate Employee PWA router download to the installer page for staff workstations.",
        "CreditSoft 0.9.26 packages the intranet-client runner with macOS/Linux and Windows installers that install only the local 127.0.0.1:8877 router.",
        "CreditSoft 0.9.26 keeps employee client installers free of Docker, databases, API keys, AI keys, tunnel tokens, and cluster SSH material.",
        "CreditSoft 0.9.25 keeps Pull next report limited to active/runnable clients unless staff explicitly starts a Recovery sweep.",
        "CreditSoft 0.9.25 bases Recovery sweep eligibility on real activity such as last report import, imported payment history, billing last-paid date, or relationship end date instead of today's database import timestamp.",
        "CreditSoft 0.9.25 keeps fresh SmartCredit reactivation failures out of Recovery sweep until they age past the comeback window, so a stopped run cannot restart the same failed accounts immediately.",
        "CreditSoft 0.9.25 keeps fired clients and invalid credentials excluded from both normal report pulls and recovery sweeps.",
        "CreditSoft 0.9.24 keeps the normal companion report queue limited to active/runnable clients unless staff explicitly starts a recovery sweep.",
        "CreditSoft 0.9.24 adds a companion Recovery sweep button for 90+ day terminated, canceled, graduated, or payment-reactivation candidates while keeping fired clients and invalid credentials excluded.",
        "CreditSoft 0.9.24 sends recovery sweeps through a separate queue_scope=reactivation API path, so Pull next report cannot accidentally process old customers.",
        "CreditSoft 0.9.24 ships browser companion 0.5.6 with the explicit recovery-sweep control.",
        "CreditSoft 0.9.23 adds a Progress & Credit Reports lane on client profiles so audits, progress reports, and credit reports stay together for the next work cycle.",
        "CreditSoft 0.9.23 keeps general Client Documents limited to supporting files instead of mixing them with audit, progress, and credit-report artifacts.",
        "CreditSoft 0.9.23 moves report-like browser captures out of Recent import records and into Progress & Credit Reports, so report artifacts are visible in one lane only.",
        "CreditSoft 0.9.23 ships browser companion 0.5.5 with report-aware DisputeFox document capture, including audit_report, progress_report, credit_report, and client_documents categories.",
        "CreditSoft 0.9.22 keeps the browser companion provider queue from processing profile-only leads, terminated relationships, blocked credentials, or SmartCredit reactivation records.",
        "CreditSoft 0.9.22 reclassifies DisputeFox profile captures that still show Lead Status as leads, even when the profile was opened directly instead of imported from the Leads list.",
        "CreditSoft 0.9.22 blocks provider accounts with invalid-credential or reactivation metadata until staff saves updated login details.",
        "CreditSoft 0.9.22 mirrors client document file payloads through cluster database sync so server nodes can restore real uploaded files instead of only metadata rows.",
        "CreditSoft 0.9.22 ships browser companion 0.5.4 with thumbnail-safe DisputeFox document capture and local client-document naming.",
        "CreditSoft 0.9.21 adds client document storage totals to the roster so staff can see who has files and how much space those dossiers use.",
        "CreditSoft 0.9.21 tightens the Clients/Leads/Terminated/Fired/Canceled/Graduated/All row and keeps it left-aligned above roster search.",
        "CreditSoft 0.9.21 fixes the client action menu text color so Fire and Graduate are readable before hover.",
        "CreditSoft 0.9.20 gives the CTO runtime and storage column more room so the server node cards no longer crowd the diagnostics panel.",
        "CreditSoft 0.9.20 makes CTO server cards fit their content instead of stretching tall when only a few nodes are online.",
        "CreditSoft 0.9.20 changes the client-storage capacity tooltip to a compact light surface with readable text.",
        "CreditSoft 0.9.19 makes the CTO server-node mesh heading use live diagnostics labels instead of hardcoded lab names.",
        "CreditSoft 0.9.19 keeps Raspberry Pi, Ryzen, M-series Mac, and future office nodes named from their actual configured node labels.",
        "CreditSoft 0.9.18 tightens the active collapsed client icon highlight so the white icon stays readable.",
        "CreditSoft 0.9.18 standardizes collapsed left-rail count badge shape and positioning across Clients and Tasks.",
        "CreditSoft 0.9.18 makes the CRM external-link marker larger without a yellow bubble and narrows Client Health by 20px on the right edge.",
        "CreditSoft 0.9.17 lets collapsed left-rail badges sit past the rail edge so high-count badges no longer distort the client icon.",
        "CreditSoft 0.9.17 lowers the client-profile First/Last sort tabs and nudges the rolodex stack tighter against the Client Health card.",
        "CreditSoft 0.9.17 pulls the client-profile action gear back inside the page edge on wide views.",
        "CreditSoft 0.9.16 relinks staged client document records to local files when the companion downloaded files but the database path was empty.",
        "CreditSoft 0.9.16 separates document records from file-backed storage on the CTO page so sparse imports do not show misleading million-client capacity math.",
        "CreditSoft 0.9.16 expands client profile document loading and marks records as staged-only when the actual file is not attached yet.",
        "CreditSoft 0.9.15 moves the CTO server-node mesh into the first viewport so Ryzen and M4 appear together instead of hiding M4 at the bottom of the page.",
        "CreditSoft 0.9.15 tightens the CTO node cards with status, CPU/load, RAM pressure, disk free space, tailnet latency, and throughput in one compact operations surface.",
        "CreditSoft 0.9.15 keeps the client storage and runtime details on the CTO page without letting them overpower the cluster view.",
        "CreditSoft 0.9.14 forces update-feed and package downloads over IPv4 so Docker containers with broken IPv6 paths can still reach updates.creditsoft.app.",
        "CreditSoft 0.9.14 updates the CTO page from the old card-heavy diagnostics screen into a cleaner server-node operations view with tighter spacing and smaller control surfaces.",
        "CreditSoft 0.9.14 teaches CTO diagnostics to read macOS and Apple Silicon memory pressure correctly so an M4 Pro with healthy pressure and zero swap is treated as a valid secondary server node instead of a failing low-memory box.",
        "CreditSoft 0.9.14 sends memory pressure, available memory, swapins, and swapouts through the cluster summary, router hints, and Nemotron advisor so client routing and recommendations use the same evidence.",
        "CreditSoft 0.9.13 updates the CTO page from the old card-heavy diagnostics screen into a cleaner server-node operations view with tighter spacing and smaller control surfaces.",
        "CreditSoft 0.9.13 teaches CTO diagnostics to read macOS and Apple Silicon memory pressure correctly so an M4 Pro with healthy pressure and zero swap is treated as a valid secondary server node instead of a failing low-memory box.",
        "CreditSoft 0.9.13 sends memory pressure, available memory, swapins, and swapouts through the cluster summary, router hints, and Nemotron advisor so client routing and recommendations use the same evidence.",
        "CreditSoft 0.9.12 adds CTO advisor action buttons that can stage the memory-saver profile, save a healthy-node router preference, and record a RAM follow-up without pretending software can install hardware.",
        "CreditSoft 0.9.12 makes the intranet client and loopback router resource-aware so new probes can prefer the healthiest configured office node instead of only taking the first or fastest response.",
        "CreditSoft 0.9.12 makes PHP OPcache and PostgreSQL Docker memory settings environment-driven so M4, Ryzen, and future office servers can tune memory pressure safely after restart.",
        "CreditSoft 0.9.11 calls OpenRouter Nemotron directly for CTO JSON recommendations so the free endpoint returns real advice instead of an empty structured wrapper payload.",
        "CreditSoft 0.9.10 moves the CTO OpenRouter Nemotron advisor to the free Nemotron Super endpoint first and strips odd bullet prefixes from generated recommendations.",
        "CreditSoft 0.9.9 makes the CTO OpenRouter Nemotron advisor prefer the working Nemotron Super endpoint first so recommendations return faster.",
        "CreditSoft 0.9.8 fixes the CTO OpenRouter Nemotron advisor by trying current Nemotron model endpoints before returning a clean setup/status message.",
        "CreditSoft 0.9.7 adds an OpenRouter Nemotron performance advisor on the CTO page that reviews CPU, memory, disk, cluster, and public speed diagnostics and returns the top three upgrade recommendations.",
        "CreditSoft 0.9.6 keeps the active client rolodex visible when the open profile is terminated or payment-blocked, without adding that profile back into active tabs.",
        "CreditSoft 0.9.6 preserves the lowered rolodex alignment from 0.9.5 so the alphabet, people tabs, and First/Last tabs sit on the Client Health card edge.",
        "CreditSoft 0.9.5 keeps terminated or payment-blocked profiles out of the active client rolodex, even when an old URL still carries view=clients.",
        "CreditSoft 0.9.5 restores the client profile people-tab row so every client in the current view is visible instead of filtering the row to only the selected alphabet letter.",
        "CreditSoft 0.9.5 lowers the profile rolodex stack another few pixels so the alphabet, people tabs, and First/Last tabs sit on the Client Health card edge instead of floating high above it.",
        "CreditSoft 0.9.4 restores the client profile people-tab row so every client in the current view is visible instead of filtering the row to only the selected alphabet letter.",
        "CreditSoft 0.9.4 lowers the profile rolodex stack so the alphabet, people tabs, and First/Last tabs sit on the Client Health card edge instead of floating high above it.",
        "CreditSoft 0.9.4 keeps the alphabet centered as a current-view index while the people tabs remain the full current-view roster.",
        "CreditSoft 0.9.3 centers the client-profile rolodex alphabet, name tabs, and previous/next controls over the Client Health card instead of stretching them across the page.",
        "CreditSoft 0.9.3 keeps First and Last attached to the Client Health card edge while the horizontal tabs center over the card body.",
        "CreditSoft 0.9.3 republishes the intranet build through the update lane so Ryzen, M4, and future office nodes can pull the same centered rolodex package.",
        "CreditSoft 0.9.2 folds Current score, Accounts reviewed, Priority disputes, and Utilization targets into the Client Health card as four clean metric panels.",
        "CreditSoft 0.9.2 moves the profile previous and next controls onto the name-tab row so the arrows travel with the people tabs instead of the alphabet index.",
        "CreditSoft 0.9.2 adds visible per-letter counts to the client rolodex alphabet so every letter shows how many names it represents in the current view.",
        "CreditSoft 0.9.2 republishes the intranet build through the update lane so Ryzen, M4, and future office nodes can pull the same package instead of relying on manual hot deploys.",
        "CreditSoft 0.9.1 fixes the Office updates apply route so browser recovery after a restart lands back on the update page instead of a 405 Method Not Allowed screen.",
        "CreditSoft 0.9.1 clears persistent Docker bootstrap cache files before Laravel boots so stale dev-only providers cannot brick an office node after an update.",
        "CreditSoft 0.9.1 records the applied build in installer state instead of rewriting .env during the update request, preventing self-update restarts from interrupting the browser response.",
        "CreditSoft 0.9.0 adds the CRM launch bridge so the left-rail CRM item uses the active intranet session, creates the CRM workspace when needed, and opens the CRM with a short-lived token instead of asking for a second password.",
        "CreditSoft 0.9.0 stores only an encrypted CRM-only hidden credential for the sidecar handoff; the intranet password remains a one-way hash and is never reused or exposed.",
        "CreditSoft 0.9.0 white-labels the CRM sidecar image during Docker builds so the welcome screen points legal links to creditsoft.app and uses CreditSoft branding assets.",
        "CreditSoft 0.9.0 removes the old Docker database-directory mount from the PostgreSQL office profile so new migration files are not hidden behind a stale SQLite-era volume.",
        "CreditSoft 0.9.0 tightens the main left rail and Meta/social rail icons to 18px so the rail lands closer to the intended compact size.",
        "CreditSoft 0.9.0 ships browser companion 0.5.3 with SmartCredit FusionAuth invalid-login handling for the real \"Invalid login credentials.\" page, so rejected provider credentials are marked needs credentials, noted internally, queued for CRM email review, and skipped while the queue keeps moving.",
        "CreditSoft 0.9.0 normalizes DisputeFox Leads list rows into the Leads roster instead of only staging them, keeps lead/intake customers out of the active client lane, and preserves lead source metadata when a profile sync exposes Lead Status.",
        "CreditSoft 0.9.0 changes the local router failure path so normal browser visits get a maintenance/reconnect page and Inertia visits get a proper reload signal instead of a plain JSON 502 modal.",
        "CreditSoft 0.9.0 ships browser companion 0.5.1 with report-first wording, explicit SmartCredit and IdentityIQ report-pull lanes, and a legacy import menu for DisputeFox plus upcoming Client Dispute Manager, Cloud Credit Repair, and white-label CRO sources.",
        "CreditSoft 0.8.6 installs rsync into the Docker intranet runtime so self-updates can overlay office packages from inside the container.",
        "CreditSoft 0.8.6 adds a PHP fallback overlay path so self-updates can still copy packages if a stripped-down runtime is missing rsync.",
        "CreditSoft 0.8.6 tightens the main left rail and Meta/social rail icons to 21px so the rail lands at the intended size.",
        "CreditSoft 0.8.6 stamps generated node installers with CREDITSOFT_APP_VERSION and CREDITSOFT_APP_BUILD so fresh installs know their actual package version.",
        "CreditSoft 0.8.5 ships browser companion 0.4.22 with SmartCredit reactivation detection, so unpaid or inactive SmartCredit accounts are marked needs client payment, noted internally, assigned a staff follow-up task, and skipped while the queue keeps moving.",
        "CreditSoft 0.8.4 ships browser companion 0.4.21 with separate DisputeFox import buttons for Import all lists, Clients, Leads, Affiliates, Invoices, Automation, Profile details, and Current page.",
        "The visible companion migration copy now says DisputeFox and legacy CRM instead of Pulse, keeping the UI language closer to what the customer recognizes.",
        "Opened DisputeFox invoice detail modals can now be captured from Current page, including invoice number, client, totals, due date, notes, and line items.",
        "CreditSoft 0.8.3 adds a Client Process Checklist to client profiles with intake, assignment, portal, onboarding, billing, report import, dispute, and letter readiness steps.",
        "The main left rail icons were reduced from the oversized pass to 26px, while HR now gets a yellow accent so it stands out without another icon container.",
        "Browser companion 0.4.20 now names Pulse profiles that fail during migration, so the retry list shows which clients or leads need attention instead of only saying a count failed.",
        "Pulse profile migration now also sweeps supporting Pulse lanes after profiles, including Invoices, Affiliates, and Automation, so access-sensitive migrations do not depend on remembering a second list-import pass.",
        "The Pulse invoice lane now opens billing_report.jsp and the server classifies billing_report / billing pages as invoice imports.",
        "Pulse list capture expands available row-count selectors before importing supporting lanes, helping invoice and affiliate lists avoid page-size cutoffs.",
        "CreditSoft 0.8.2 groups the main left rail into Workspace and Operations sections with a clean divider between daily work and management tools.",
        "The left rail can now expand from icon-only mode into labeled navigation, then collapse back to the tighter workspace view.",
        "Main rail icons are larger and hover feedback is faster so the rail feels easier to hit and less sluggish.",
        "CreditSoft 0.8.1 adds Chart.js HR activity visuals: a per-employee daily activity line chart, a 24-hour work-pattern line chart, and activity-window cards showing peak hour, usual span, active days, and last event.",
        "Payroll now uses the provided Sendwave SVG as a plain logo image without putting the logo inside another frame.",
        "CreditSoft 0.8.0 adds HR and Payroll as first-class intranet lanes with left-rail icons, employee files, performance mix, reviews, write-ups, onboarding notes, saved pay methods, payroll ledger records, and Sendwave referral guidance.",
        "Browser companion 0.4.19 raises Pulse profile processing to 500 visible profiles per run, so a 341-lead list is not stopped at the old 120-profile safety cap.",
        "CreditSoft 0.7.15 raises Pulse list intake to 2,000 rows so full Leads lists such as 341 rows are not cut off at 250.",
        "Pulse Leads and Affiliates captures now update the existing staged capture for that page instead of creating duplicate staged imports every time the companion is run.",
        "CreditSoft 0.7.14 stages Pulse Leads as lead import captures instead of creating client roster rows from the leads list.",
        "The Clients page now separates Clients, Leads, and All so imported Pulse leads do not make the active client roster look inflated.",
        "CreditSoft 0.7.13 pins Pulse Secret Key fields to IdentityIQ only, so SmartCredit, MyScoreIQ, and other provider rows do not inherit an IdentityIQ-only security value.",
        "CreditSoft 0.7.12 fixes Pulse / DisputeFox profile reimport so Account and Monitoring fields hidden inside tabs or modals can be captured intentionally instead of being dropped by the visible-field filter.",
        "Browser companion 0.4.17 captures Pulse profile DOB, SSN, monitoring agency, provider username, provider password, and secret-key fields from the hidden Account and Monitoring surfaces.",
        "Pulse monitoring-agency IDs now map into provider rows for IdentityIQ, SmartCredit, and MyScoreIQ, including CreditSmart wording when Pulse uses that label.",
        "The client roster now keeps the provider-login signal compact with a simple Login column that says SmartCredit, IdentityIQ, MyScoreIQ, or No saved login instead of adding bulky audit cards.",
        "CreditSoft 0.7.11 removes the intranet-wide floating bug-report/page-actions gear so pages no longer render dual upper-right gears.",
        "The page feedback modal, event wiring, and /internal/page-feedback route were removed from the intranet runtime.",
        "Workspace action menus keep their real navigation items but no longer show a Submit bug report action.",
        "CreditSoft 0.7.10 adds /cto as a real main workspace page and redirects the old /settings/cto path to it.",
        "The main rail now includes a CTO icon beside CFO, while the settings sidebar no longer treats CTO like a settings subpage.",
        "Violations are easier to find again: the CFO Open violations metric and the footer Violations link both open /violations.",
        "CreditSoft 0.7.9 changes License / Office included access into three stacked rows instead of a wrapped two-column line.",
        "Included access now says Included or Not included instead of showing Enabled or Off.",
        "Office profile now reads as three rows for Company, Admin Email, and Tailscale Host instead of crowding all three values across one row.",
        "CreditSoft 0.7.8 restores violations as a first-class left-rail item with a warning icon and a real /violations review queue.",
        "The old /ops shortcut now lands on the violations queue so existing links and the 43-count badge reach the actual review work instead of Connectivity.",
        "The License / Office updates changelog is now grouped by CreditSoft version, with the latest version expanded by default and older versions tucked under their own disclosures.",
        "CreditSoft 0.7.7 adds the live z@creditsoft.app Zelle QR image to the intranet assets and uses it on the License / Office renewal card.",
        "The renewal payment copy now says to scan the live Zelle QR instead of calling the code a placeholder.",
        "The update-lane checkout and renewal pages now prefer the same live Zelle QR asset before falling back to generated QR text.",
        "CreditSoft 0.7.6 makes left-rail count badges 10% larger and uses one amber count style so the Tasks badge matches the rest of the intranet rail.",
        "The Ops violation count no longer appears while viewing settings pages such as Connectivity, so the settings rail does not show an unexplained 43.",
        "Task board action and status badges now use the same larger rounded count/action language as the rest of the app.",
        "CreditSoft 0.7.5 reshapes the CTO diagnostics page so the current node card uses one column with three ledger rows instead of three cramped mini cards.",
        "Client storage footprint now gets four full-width rows for biggest client, smallest client, average client, and estimated remaining capacity.",
        "The hardware hero strip now includes Staff activity, showing the most active and quietest staff member from recent audit events.",
        "Cluster view now uses a topology summary for mode, local office, online offices, and remote peers instead of repeating memory, disk, and network totals.",
        "PostgreSQL diagnostics now use a shorter server-version lookup so the runtime line no longer reads as PostgreSQL PostgreSQL.",
        "CreditSoft 0.7.4 flattens the License / Office updates page so update stats, license details, included access, office profile, and Zelle renewal fields read as clean ledger rows instead of boxes inside boxes.",
        "The license key area now uses shorter helper text that does not clip on mobile, while action links stay as plain icon actions instead of pill buttons.",
        "The Zelle renewal fields now sit under the centered QR code as quiet line items, keeping the live license price, 10% Zelle discount, destination, memo, and total visible without extra card chrome.",
        "CreditSoft 0.7.3 looks up the current license/plan price for Zelle payment lanes and shows the 10% Zelle discount beside the QR code.",
        "Public checkout and renewal pages now show plan price, Zelle discount, and Zelle total under the centered QR code.",
        "The intranet License / Office updates page now derives the Zelle renewal amount from the active license plan when no manual renewal amount is configured.",
        "Zelle QR blocks now clearly label the generated code as a placeholder until the live Zelle QR is connected.",
        "CreditSoft 0.7.2 replaces the remaining pill-style update and license buttons with plain icon actions.",
        "Feature availability now uses compact dot labels instead of pill badges, keeping the License / Office updates page cleaner for screenshots.",
        "CreditSoft 0.7.1 fixes the internal office package download route so already-current installs can download the staged package without a 500 error.",
        "The License / Office updates page now puts update actions at the top, hides the long changelog behind a disclosure arrow, and removes the filled-pill treatment from status indicators.",
        "The renewal QR block now centers the QR code and moves the payment fields underneath it for cleaner screenshots and better mobile flow.",
        "CreditSoft 0.7.0 moves the intranet onto PostgreSQL and fixes the full SQLite-to-PostgreSQL cutover path.",
        "PostgreSQL-strict foreign key ordering is fixed for bureau snapshots/reporting cycles and SOP runs/templates.",
        "The SQLite-to-PostgreSQL copier now handles tables without id columns and collapses duplicate unique-key seed rows instead of blocking the migration.",
        "The Docker PostgreSQL service now exposes a configurable host port so the existing local intranet process can use Docker Postgres without starting the full web container.",
        "Browser companion 0.4.16 can attach SmartCredit, IdentityIQ, MyScoreIQ, and Credit Karma provider rows when a Pulse profile exposes saved provider login fields.",
        "Pulse profile matching now stores and checks source record IDs from both list pages and profile pages so imported people do not split into duplicate client records as easily.",
        "The companion Update action can now force a provider report pass from the button, while background queue checks still respect next-due timing.",
        "Browser companion 0.4.15 separates the language into two lanes: Import brings legacy CRM data from DisputeFox/Pulse, while Update pulls fresh reports from providers like SmartCredit and IdentityIQ.",
        "The default side panel now says Update / Provider reports with an Update button, report-update queue language, and report-pull empty states.",
        "The logo import menu now opens Import / DisputeFox import with Import profiles, Import lists, and Import page actions for legacy CRM records, saved reports, documents, invoices, leads, and workflows.",
        "Browser companion 0.4.14 unifies the Pulse source and the normal provider flow under one client-processing lane so the panel no longer reads like three separate tools.",
        "Pulse / DisputeFox now uses the primary Process action to open client and lead profiles, sync full details, and stage/download reports and documents where Pulse allows file access.",
        "Import lists now only stages visible Pulse rows. The old separate-flow wording was removed from the companion surface so it is clearer what each button does.",
        "Opening the import systems menu no longer triggers SmartCredit/IdentityIQ provider queue checks, which prevents misleading no client-ready messages while working in Pulse.",
        "Browser companion 0.4.13 adds a Process profiles action for Pulse Clients and Leads. It opens visible profile pages, syncs full client details, and imports reports/documents from the logged-in Pulse session where Pulse exposes file access.",
        "Pulse credit reports are now included in document capture instead of being filtered out before import.",
        "Pulse list capture now keeps up to 250 visible rows per list so profile processing can cover larger imported pages.",
        "Browser companion 0.4.12 makes the side panel and popup bodies scroll under a fixed compact header, so long Pulse activity remains reachable.",
        "The large Office pairing block was removed from the companion surfaces; the green status dot now carries the API key state and the larger plain gear opens settings.",
        "The normal provider lane now uses shorter copy and a smaller Process button so the activity log has more working room.",
        "Browser companion 0.4.11 clears the old Pulse import breadcrumbs when the full pass finishes, so Automation opening/reading lines no longer make a completed import look stuck.",
        "Pulse list import now ends with one summary line showing which lanes imported and then returns the companion to normal CreditSoft client processing.",
        "Browser companion 0.4.10 separates the Pulse source from normal SmartCredit and IdentityIQ client processing, so Pulse pages no longer hijack the regular provider lane after Pulse work is done.",
        "The side panel now has a dedicated Import lists button that walks Pulse Clients, Leads, Invoices, Affiliates, and Automation instead of stopping after the first visible list page.",
        "The Pulse source card now includes a Done button that turns the source off and returns the companion to normal CreditSoft client processing.",
        "Pulse invoice, lead, affiliate, and datatable-shaped pages now use broader table detection so visible rows can be imported even when Pulse changes table ids/classes.",
        "Browser companion 0.4.9 detects Pulse client documents from the logged-in browser session, stages document metadata on the matched CreditSoft client, and attempts authenticated file uploads when Pulse exposes usable download URLs.",
        "CreditSoft now has a browser-companion client-document API endpoint so Pulse files can be upserted without duplicate document records.",
        "The visible tiny-dot credential copy was removed from the companion; Pulse credentials now live behind the CreditSoft logo/import menu.",
        "Companion sync status now reports document records and imported files instead of repeating only the profile sync result.",
        "Browser companion 0.4.8 imports Pulse list pages instead of stopping after the first opened profile.",
        "Pulse Leads and Clients tables now create or update CreditSoft client records directly from visible list rows.",
        "Pulse Invoices and Billing rows now create or update imported client payment records tied to the matched or stubbed client.",
        "Pulse Affiliates and other business lists are staged as imported browser-companion list captures for review instead of being discarded after detection.",
        "Browser companion 0.4.7 hardens Pulse profile capture so visible customer selectors win over hidden modal fields.",
        "Pulse customer account pages now sync the visible name, email, phone, DOB, SSN, source IDs, address, and assigned staff instead of grabbing unrelated hidden form junk.",
        "CreditSoft now includes the creditsoft:database:migrate-postgres command to copy the current SQLite office data into a PostgreSQL office database when the node is ready.",
        "The Docker office profile can start CreditSoft, queue, scheduler, PostgreSQL, local router, and the white-label CRM sidecar together.",
        "Generated installers now support --office on macOS/Linux and -Office on Windows to enable PostgreSQL, router, and CRM sidecar support in one path.",
        "CTO storage diagnostics now show the real database engine, database location, and engine-specific database size instead of assuming SQLite forever.",
        "The Profile settings page now gets a wide workspace so the personal API key and pairing panels no longer collapse into narrow slivers.",
        "The intranet information rail item now uses a plain centered i icon inside the same full-size rail hit area as the puzzle and gear icons.",
        "The circle-info glyph was removed from the rail because it still looked like a tiny badge even after being moved above the puzzle icon.",
        "The intranet information icon is now a normal left-rail item above the browser companion puzzle icon.",
        "The information icon no longer overlays the puzzle icon or reads like a notification badge.",
        "Footer storage and connector popovers now use the new light-card tooltip surface with matching white arrows.",
        "Footer popover text now matches the visible surface, so storage, backup, Tailscale, ngrok, Wasabi, Dropbox, and Google Drive tips are readable.",
        "CreditSoft OPS now stores reusable automation discoveries separately from client captures, with first/last seen tracking, source IDs, workflow counts, condition counts, action counts, and step counts.",
        "The browser companion can detect DisputeFox / Pulse Automation workflow detail pages and workflow list pages, then post sanitized workflow structure to CreditSoft instead of trying to force those pages into a client profile.",
        "Automation discoveries capture workflow names, status, category, workflow type, start condition, available trigger conditions, action types, visible steps, and action labels without sending the full page DOM to the automation library.",
        "The OPS screen now has an Automation discoveries review panel so owner admins can see newly spotted workflows before deciding whether a pattern should become a global CreditSoft automation.",
        "The Pulse multiple simultaneous logins prompt no longer stops the companion after clicking Continue and Logout other sessions; the companion resumes processing the page after the prompt clears.",
        "The browser companion package is now 0.4.9 and includes DisputeFox documents, DisputeFox list importing, the automation discovery parser, OPS discovery endpoint, and hardened DisputeFox profile selector capture.",
        "The intranet footer/status rail is now a single compact grey row instead of becoming a tall white slab.",
        "The footer no longer shows a separate Apply Update button; the available-version text and small update icon are the clue that a package is waiting.",
        "Clicking the footer version pill now opens the License / Office updates page instead of only re-checking and flashing a ready message.",
        "The License / Office updates page now has the real Check for updates and Apply update controls, with package download kept as a separate backup action.",
        "The Chrome app install control now disappears after the PWA is installed, so the footer no longer shows a confusing Installed pill beside update status.",
        "The storage snapshot, connector health dots, update badge, install control, reload action, and Ops link have tighter spacing, smaller tracking, and less visual noise.",
        "Long update safety guidance no longer forces the footer to wrap on 13-inch and 15-inch displays; it only appears when there is enough horizontal room.",
        "The companion now treats legacy CRM pages as either one profile or a record list, so Clients, Leads, Affiliates, and Invoices are not mistaken for a single client profile.",
        "Pulse client account and overview pages now expose source record IDs, visible profile fields, score/detail rows, and page kind metadata through the browser companion sync.",
        "On Pulse client/lead grids, Process / Sync page opens the selected row, or the first visible row, before importing so list pages do not create bad profile matches.",
        "Pulse invoice and affiliate pages are detected as business lists and exposed as row-shaped table data for the next list-import lane instead of being redirected into the client queue.",
        "When the active tab is Pulse, the side panel Process button now opens Pulse Clients or syncs the current Pulse client profile instead of searching for a SmartCredit-style client-ready account.",
        "The companion now detects the Pulse multiple simultaneous logins modal and clicks Continue and Logout other sessions before trying to process the page.",
        "The DisputeFox source item now opens https://pulse.disputeprocess.com/jsp/client/login.jsp?cdn/ when the active tab is not already on Pulse.",
        "Companion copy now says DisputeFox / Pulse and Pulse credentials instead of implying the login starts at plain DisputeFox.com.",
        "The Pulse importer now reads old-school table rows, label/value text, definition lists, body lines, and same-tab frames instead of only modern input fields.",
        "If Pulse still does not expose a recognizable client profile, the companion reports the labels it did see so the mapper can be tightened quickly.",
        "Clicking the companion wordmark now opens an actual dropdown under the logo instead of only revealing a lower hidden section.",
        "The side panel now registers the logo click handler correctly, so the import menu works in the main companion surface.",
        "The regular browser companion can sync detected DisputeFox account/profile fields through the main browser companion API feature.",
        "Clicking the companion wordmark opens the customer import systems menu; DisputeFox / Pulse is the first source system and the local credential form stays behind that logo menu.",
        "The generated node installer advertises CRM sidecar controls instead of the upstream CRM product name.",
        "The office stack can run one PostgreSQL server while keeping CreditSoft and CRM data in separate databases and users.",
        "CRM images stay independently updatable through the Docker profile so upstream releases can be pulled without rebuilding the intranet app."
    ],
    "download_url": "https://updates.creditsoft.app/downloads/creditsoft-office-v2026.4.21.38.zip",
    "crm_sidecar": {
        "label": "CreditSoft CRM Sidecar",
        "image": "update.creditsoft.app/creditsoft/crm-sidecar:latest",
        "update_strategy": "docker_pull",
        "source_visible_to_customer": false
    },
    "browser_companion": {
        "label": "CreditSoft Browser Companion",
        "latest_version": "0.5.10",
        "download_url": "https://updates.creditsoft.app/downloads/creditsoft-browser-companion-v0.5.10.zip",
        "trial_days": 7,
        "trial_label": "7-day companion trial",
        "renewal_url": "https://updates.creditsoft.app/renewal/"
    },
    "intranet_client": {
        "label": "CreditSoft Employee Intranet Client",
        "latest_version": "0.1.2",
        "download_url": "https://updates.creditsoft.app/downloads/creditsoft-intranet-client-installer-v0.1.2.zip",
        "router_url": "http://127.0.0.1/dashboard?source=intranet-client"
    },
    "browser_companion_url": "https://updates.creditsoft.app/downloads/creditsoft-browser-companion-v0.5.10.zip",
    "renewal_url": "https://updates.creditsoft.app/renewal/",
    "support_url": "https://creditsoft.app/",
    "minimum_version": "0.5.3",
    "update_required": false
}
