{
    "product": "CreditSoft Intranet",
    "channel": "stable",
    "latest_version": "2026.4.28.6",
    "latest_build": "2026.4.28.6",
    "published_at": "2026-04-28T11:52:22-07:00",
    "headline": "CreditSoft 2026.4.28.6 CRM PWA bridge is ready",
    "summary": "Keeps the CRM inside the CreditSoft PWA and restores the existing CRM-user recovery/roster bridge.",
    "notes": [
        "CreditSoft 2026.4.28.6 changes the left-rail CRM item to open a same-origin /crm workspace so installed PWA sessions do not jump to the regular browser.",
        "CreditSoft 2026.4.28.6 restores the CRM launch bridge logic that repairs existing CRM users, retries token login, and syncs the CreditSoft roster into the CRM sidecar.",
        "CreditSoft 2026.4.28.5 mirrors provider, tunnel, mail, payment, CRM, and backup env families into the generated Laravel .env so web requests see OpenRouter and related keys after container recreates.",
        "CreditSoft 2026.4.28.5 excludes real .env secret files from Docker build context while keeping env example templates available.",
        "CreditSoft 2026.4.28.4 fixes the CRM launch bridge so an existing remote CRM user redirects to the CRM instead of causing an intranet 500.",
        "CreditSoft 2026.4.28.4 mirrors Docker env values into the generated Laravel .env so web session routes keep APP_KEY after container restarts.",
        "CreditSoft 2026.4.28.4 adds a workspace doctor and release guard so update packages refuse to build from detached Desktop or iCloud drift copies.",
        "CreditSoft 2026.4.28.3 fixes the office update package by stripping dev-only Composer provider metadata from production update zips, preventing Laravel Boost discovery from causing a 500 after install.",
        "CreditSoft 2026.4.28.3 keeps the release on the date-version format for the intranet, browser companion, and installer metadata.",
        "CreditSoft 2026.4.28.2 creates checkout reference numbers before payment and shows Zelle plus Cash App with QR codes, amounts, $creditsoft, links, and required memo text.",
        "CreditSoft 2026.4.28.2 creates renewal reference numbers before payment and applies the same memo/note rule to Zelle and Cash App renewals.",
        "CreditSoft 2026.4.28.2 matches trusted Zelle and Cash App payment mail against checkout and renewal references as well as email, amount, phone, and payer details.",
        "CreditSoft 2026.4.28.1 adds Cash App/Square trusted payment-mail detection to the admin payment checker so matching notices can trigger license creation, renewal, receipts, and balance-due handling.",
        "CreditSoft 2026.4.28.1 stores the detected payment provider on payment messages so Cash App receipts and logs no longer have to masquerade as Zelle.",
        "CreditSoft 2026.4.28.1 updates the checkout and renewal lanes to tell customers to enter their Zelle or Cash App payment source for matching.",
        "CreditSoft 2026.4.28.1 builds office zips with no-script no-dev autoload dumps so dev-only providers cannot block release packaging.",
        "CreditSoft 2026.4.28.1 clears Laravel package discovery cache before no-dev package builds so stale dev providers cannot block the office update zip.",
        "CreditSoft 2026.4.27.2 uses Local/Remote plus detected OS for CTO node names instead of inferred capacity or personal hardware labels.",
        "CreditSoft 2026.4.27.2 keeps architecture, CPU cores, RAM, disk, and pressure data in the diagnostics detail rows where they belong.",
        "CreditSoft 2026.4.27.1 collapses the local Docker runtime self-view into the real host-level office node so CTO shows the actual two-node cluster.",
        "CreditSoft 2026.4.27.1 uses host-level memory, disk, load, and network diagnostics for the local CTO node when the app runs inside Docker.",
        "CreditSoft 2026.4.27.1 removes the stale Local Docker runtime fallback label from CTO diagnostics.",
        "CreditSoft 2026.4.27.1 keeps the date-version release marker aligned after the April 27 office fixes.",
        "CreditSoft 2026.4.25.1 uses the date release format across current office, installer, companion, client, and update-feed surfaces.",
        "CreditSoft 2026.4.25.1 prevents stale legacy 0.x installer state from overriding a packaged date-format release.",
        "CreditSoft 2026.4.25.1 removes the Docker .env bind mount so M-series Mac nodes can start from the standard /Library/Application Support path.",
        "CreditSoft 2026.4.25.1 generates the Laravel .env file from container environment values when a bind-mounted .env file is missing.",
        "CreditSoft 2026.4.25.1 syncs active lifetime license state across approved server nodes so M4 and Ryzen show the same license.",
        "CreditSoft 2026.4.25.1 corrects the release date to April 25 Pacific time while keeping cluster license sync active.",
        "CreditSoft 2026.4.26.2 syncs active lifetime license state across approved server nodes so M4 and Ryzen show the same license.",
        "CreditSoft 2026.4.26.2 resets PHP OPcache after office package overlays so new routes load without stale route tables.",
        "CreditSoft 2026.4.26.1 syncs active lifetime license state across approved server nodes so M4 and Ryzen show the same license.",
        "CreditSoft 2026.4.26.1 adds an encrypted cluster license outbox so offline server nodes receive the license when they come back.",
        "CreditSoft 2026.4.22.7 Dashboard Brag rights is now Website proof metrics with a copyable widget snippet.",
        "CreditSoft 2026.4.22.7 Credit Sense can proxy office impact stats through /api/creditsoft-office-stats.php without exposing an API token in browser code.",
        "CreditSoft 2026.4.22.6 Clients with DisputeFox document links now show metadata-only inventory separately from real file bytes.",
        "CreditSoft 2026.4.22.6 The roster now lists missing required documents instead of treating links or thumbnails as complete files.",
        "CreditSoft 2026.4.22.6 The companion document capture scans more DisputeFox document rows and skips tiny preview/thumbnail payloads when a real download URL exists.",
        "CreditSoft 2026.4.22.5 streams cluster backup uploads so large database archives do not exhaust PHP memory.",
        "CreditSoft 2026.4.22.5 keeps cluster document sync from inserting metadata-only document records with a null file path.",
        "CreditSoft 2026.4.22.4 keeps cluster document sync from inserting metadata-only document records with a null file path.",
        "CreditSoft 2026.4.22.3 fixes client roster sorting on PostgreSQL for Files, Provider, Owner, and Cycle headers.",
        "CreditSoft 2026.4.22.2 updates the office build.",
        "CreditSoft 2026.4.22.1 always checks the canonical public update feed even when a node has a bundled local feed, then chooses the newest available feed between public and local sources.",
        "CreditSoft 2026.4.21.44 uses the public release version as the build identifier so CTO diagnostics, installers, update feeds, and package manifests all show the same number.",
        "CreditSoft 2026.4.21.43 keeps office update archives production-only by excluding every Composer dev package from the vendor payload.",
        "CreditSoft 2026.4.21.43 marks Boost MCP Roster Pail Sail and Collision as never-discovered in office production builds so queue scheduler and web containers share safe bootstrap cache.",
        "CreditSoft 2026.4.21.43 raises PHP post body and upload limits to 1024M so cluster backup mirroring can receive real office archives instead of falling into 413 errors.",
        "CreditSoft 2026.4.21.42 keeps office update archives production-only by excluding every Composer dev package from the vendor payload.",
        "CreditSoft 2026.4.21.42 marks Boost MCP Roster Pail Sail and Collision as never-discovered in office production builds so queue scheduler and web containers share safe bootstrap cache.",
        "CreditSoft 2026.4.21.41 prevents dev-only Laravel providers from being discovered in production office builds so web, queue, and scheduler containers share a safe bootstrap cache.",
        "CreditSoft 2026.4.21.41 raises the default Docker PHP memory limit to 512 MB while keeping it configurable through PHP_MEMORY_LIMIT.",
        "CreditSoft 2026.4.21.41 keeps office update packages from shipping dev-only Laravel vendor packages that can poison shared bootstrap cache.",
        "CreditSoft 2026.4.21.40 changes archived lifecycle processing dots from grey to blue so grey no longer reads as disabled while hover text explains the archived state.",
        "CreditSoft 2026.4.21.39 changes the client-name roster dot from vague billing grey to processing status: green for ready/current, red for work needed, amber for intake, and neutral for inactive lifecycle records.",
        "CreditSoft 2026.4.21.38 moves the roster stage links back to the right of search and tightens the client table width.",
        "CreditSoft 2026.4.21.38 adds date-based release versions using YYYY.M.D.N for update packages and feed publishing.",
        "The visible companion migration copy now says DisputeFox and legacy CRM instead of Pulse, keeping the UI language closer to what the customer recognizes.",
        "Opened DisputeFox invoice detail modals can now be captured from Current page, including invoice number, client, totals, due date, notes, and line items.",
        "The main left rail icons were reduced from the oversized pass to 26px, while HR now gets a yellow accent so it stands out without another icon container.",
        "Pulse profile migration now also sweeps supporting Pulse lanes after profiles, including Invoices, Affiliates, and Automation, so access-sensitive migrations do not depend on remembering a second list-import pass.",
        "The Pulse invoice lane now opens billing_report.jsp and the server classifies billing_report / billing pages as invoice imports.",
        "Pulse list capture expands available row-count selectors before importing supporting lanes, helping invoice and affiliate lists avoid page-size cutoffs.",
        "The left rail can now expand from icon-only mode into labeled navigation, then collapse back to the tighter workspace view.",
        "Main rail icons are larger and hover feedback is faster so the rail feels easier to hit and less sluggish.",
        "Payroll now uses the provided Sendwave SVG as a plain logo image without putting the logo inside another frame.",
        "Pulse Leads and Affiliates captures now update the existing staged capture for that page instead of creating duplicate staged imports every time the companion is run.",
        "The Clients page now separates Clients, Leads, and All so imported Pulse leads do not make the active client roster look inflated.",
        "Pulse monitoring-agency IDs now map into provider rows for IdentityIQ, SmartCredit, and MyScoreIQ, including CreditSmart wording when Pulse uses that label.",
        "The client roster now keeps the provider-login signal compact with a simple Login column that says SmartCredit, IdentityIQ, MyScoreIQ, or No saved login instead of adding bulky audit cards.",
        "The page feedback modal, event wiring, and /internal/page-feedback route were removed from the intranet runtime.",
        "Workspace action menus keep their real navigation items but no longer show a Submit bug report action.",
        "The main rail now includes a CTO icon beside CFO, while the settings sidebar no longer treats CTO like a settings subpage.",
        "Violations are easier to find again: the CFO Open violations metric and the footer Violations link both open /violations.",
        "Included access now says Included or Not included instead of showing Enabled or Off.",
        "Office profile now reads as three rows for Company, Admin Email, and Tailscale Host instead of crowding all three values across one row.",
        "The old /ops shortcut now lands on the violations queue so existing links and the 43-count badge reach the actual review work instead of Connectivity.",
        "The License / Office updates changelog is now grouped by CreditSoft version, with the latest version expanded by default and older versions tucked under their own disclosures.",
        "The renewal payment copy now says to scan the live Zelle QR instead of calling the code a placeholder.",
        "The update-lane checkout and renewal pages now prefer the same live Zelle QR asset before falling back to generated QR text.",
        "The Ops violation count no longer appears while viewing settings pages such as Connectivity, so the settings rail does not show an unexplained 43.",
        "Task board action and status badges now use the same larger rounded count/action language as the rest of the app.",
        "Client storage footprint now gets four full-width rows for biggest client, smallest client, average client, and estimated remaining capacity.",
        "The hardware hero strip now includes Staff activity, showing the most active and quietest staff member from recent audit events.",
        "Cluster view now uses a topology summary for mode, local office, online offices, and remote peers instead of repeating memory, disk, and network totals.",
        "PostgreSQL diagnostics now use a shorter server-version lookup so the runtime line no longer reads as PostgreSQL PostgreSQL.",
        "The license key area now uses shorter helper text that does not clip on mobile, while action links stay as plain icon actions instead of pill buttons.",
        "The Zelle renewal fields now sit under the centered QR code as quiet line items, keeping the live license price, 10% Zelle discount, destination, memo, and total visible without extra card chrome.",
        "Public checkout and renewal pages now show plan price, Zelle discount, and Zelle total under the centered QR code.",
        "The intranet License / Office updates page now derives the Zelle renewal amount from the active license plan when no manual renewal amount is configured.",
        "Zelle QR blocks now clearly label the generated code as a placeholder until the live Zelle QR is connected.",
        "Feature availability now uses compact dot labels instead of pill badges, keeping the License / Office updates page cleaner for screenshots.",
        "The License / Office updates page now puts update actions at the top, hides the long changelog behind a disclosure arrow, and removes the filled-pill treatment from status indicators.",
        "The renewal QR block now centers the QR code and moves the payment fields underneath it for cleaner screenshots and better mobile flow.",
        "PostgreSQL-strict foreign key ordering is fixed for bureau snapshots/reporting cycles and SOP runs/templates.",
        "The SQLite-to-PostgreSQL copier now handles tables without id columns and collapses duplicate unique-key seed rows instead of blocking the migration.",
        "The Docker PostgreSQL service now exposes a configurable host port so the existing local intranet process can use Docker Postgres without starting the full web container.",
        "Pulse profile matching now stores and checks source record IDs from both list pages and profile pages so imported people do not split into duplicate client records as easily.",
        "The companion Update action can now force a provider report pass from the button, while background queue checks still respect next-due timing.",
        "The default side panel now says Update / Provider reports with an Update button, report-update queue language, and report-pull empty states.",
        "The logo import menu now opens Import / DisputeFox import with Import profiles, Import lists, and Import page actions for legacy CRM records, saved reports, documents, invoices, leads, and workflows.",
        "Pulse / DisputeFox now uses the primary Process action to open client and lead profiles, sync full details, and stage/download reports and documents where Pulse allows file access.",
        "Import lists now only stages visible Pulse rows. The old separate-flow wording was removed from the companion surface so it is clearer what each button does.",
        "Opening the import systems menu no longer triggers SmartCredit/IdentityIQ provider queue checks, which prevents misleading no client-ready messages while working in Pulse.",
        "Pulse credit reports are now included in document capture instead of being filtered out before import.",
        "Pulse list capture now keeps up to 250 visible rows per list so profile processing can cover larger imported pages.",
        "The large Office pairing block was removed from the companion surfaces; the green status dot now carries the API key state and the larger plain gear opens settings.",
        "The normal provider lane now uses shorter copy and a smaller Process button so the activity log has more working room.",
        "Pulse list import now ends with one summary line showing which lanes imported and then returns the companion to normal CreditSoft client processing.",
        "The side panel now has a dedicated Import lists button that walks Pulse Clients, Leads, Invoices, Affiliates, and Automation instead of stopping after the first visible list page.",
        "The Pulse source card now includes a Done button that turns the source off and returns the companion to normal CreditSoft client processing.",
        "Pulse invoice, lead, affiliate, and datatable-shaped pages now use broader table detection so visible rows can be imported even when Pulse changes table ids/classes.",
        "CreditSoft now has a browser-companion client-document API endpoint so Pulse files can be upserted without duplicate document records.",
        "The visible tiny-dot credential copy was removed from the companion; Pulse credentials now live behind the CreditSoft logo/import menu.",
        "Companion sync status now reports document records and imported files instead of repeating only the profile sync result.",
        "Pulse Leads and Clients tables now create or update CreditSoft client records directly from visible list rows.",
        "Pulse Invoices and Billing rows now create or update imported client payment records tied to the matched or stubbed client.",
        "Pulse Affiliates and other business lists are staged as imported browser-companion list captures for review instead of being discarded after detection.",
        "Pulse customer account pages now sync the visible name, email, phone, DOB, SSN, source IDs, address, and assigned staff instead of grabbing unrelated hidden form junk.",
        "CreditSoft now includes the creditsoft:database:migrate-postgres command to copy the current SQLite office data into a PostgreSQL office database when the node is ready.",
        "The Docker office profile can start CreditSoft, queue, scheduler, PostgreSQL, local router, and the white-label CRM sidecar together.",
        "Generated installers now support --office on macOS/Linux and -Office on Windows to enable PostgreSQL, router, and CRM sidecar support in one path.",
        "CTO storage diagnostics now show the real database engine, database location, and engine-specific database size instead of assuming SQLite forever.",
        "The Profile settings page now gets a wide workspace so the personal API key and pairing panels no longer collapse into narrow slivers.",
        "The intranet information rail item now uses a plain centered i icon inside the same full-size rail hit area as the puzzle and gear icons.",
        "The circle-info glyph was removed from the rail because it still looked like a tiny badge even after being moved above the puzzle icon.",
        "The intranet information icon is now a normal left-rail item above the browser companion puzzle icon.",
        "The information icon no longer overlays the puzzle icon or reads like a notification badge.",
        "Footer storage and connector popovers now use the new light-card tooltip surface with matching white arrows.",
        "Footer popover text now matches the visible surface, so storage, backup, Tailscale, ngrok, Wasabi, Dropbox, and Google Drive tips are readable.",
        "CreditSoft OPS now stores reusable automation discoveries separately from client captures, with first/last seen tracking, source IDs, workflow counts, condition counts, action counts, and step counts.",
        "The browser companion can detect DisputeFox / Pulse Automation workflow detail pages and workflow list pages, then post sanitized workflow structure to CreditSoft instead of trying to force those pages into a client profile.",
        "Automation discoveries capture workflow names, status, category, workflow type, start condition, available trigger conditions, action types, visible steps, and action labels without sending the full page DOM to the automation library.",
        "The OPS screen now has an Automation discoveries review panel so owner admins can see newly spotted workflows before deciding whether a pattern should become a global CreditSoft automation.",
        "The Pulse multiple simultaneous logins prompt no longer stops the companion after clicking Continue and Logout other sessions; the companion resumes processing the page after the prompt clears.",
        "The browser companion package now follows the CreditSoft date-version release and includes DisputeFox documents, DisputeFox list importing, the automation discovery parser, OPS discovery endpoint, and hardened DisputeFox profile selector capture.",
        "The intranet footer/status rail is now a single compact grey row instead of becoming a tall white slab.",
        "The footer no longer shows a separate Apply Update button; the available-version text and small update icon are the clue that a package is waiting.",
        "Clicking the footer version pill now opens the License / Office updates page instead of only re-checking and flashing a ready message.",
        "The License / Office updates page now has the real Check for updates and Apply update controls, with package download kept as a separate backup action.",
        "The Chrome app install control now disappears after the PWA is installed, so the footer no longer shows a confusing Installed pill beside update status.",
        "The storage snapshot, connector health dots, update badge, install control, reload action, and Ops link have tighter spacing, smaller tracking, and less visual noise.",
        "Long update safety guidance no longer forces the footer to wrap on 13-inch and 15-inch displays; it only appears when there is enough horizontal room.",
        "The companion now treats legacy CRM pages as either one profile or a record list, so Clients, Leads, Affiliates, and Invoices are not mistaken for a single client profile.",
        "Pulse client account and overview pages now expose source record IDs, visible profile fields, score/detail rows, and page kind metadata through the browser companion sync.",
        "On Pulse client/lead grids, Process / Sync page opens the selected row, or the first visible row, before importing so list pages do not create bad profile matches.",
        "Pulse invoice and affiliate pages are detected as business lists and exposed as row-shaped table data for the next list-import lane instead of being redirected into the client queue.",
        "When the active tab is Pulse, the side panel Process button now opens Pulse Clients or syncs the current Pulse client profile instead of searching for a SmartCredit-style client-ready account.",
        "The companion now detects the Pulse multiple simultaneous logins modal and clicks Continue and Logout other sessions before trying to process the page.",
        "The DisputeFox source item now opens https://pulse.disputeprocess.com/jsp/client/login.jsp?cdn/ when the active tab is not already on Pulse.",
        "Companion copy now says DisputeFox / Pulse and Pulse credentials instead of implying the login starts at plain DisputeFox.com.",
        "The Pulse importer now reads old-school table rows, label/value text, definition lists, body lines, and same-tab frames instead of only modern input fields.",
        "If Pulse still does not expose a recognizable client profile, the companion reports the labels it did see so the mapper can be tightened quickly.",
        "Clicking the companion wordmark now opens an actual dropdown under the logo instead of only revealing a lower hidden section.",
        "The side panel now registers the logo click handler correctly, so the import menu works in the main companion surface.",
        "The regular browser companion can sync detected DisputeFox account/profile fields through the main browser companion API feature.",
        "Clicking the companion wordmark opens the customer import systems menu; DisputeFox / Pulse is the first source system and the local credential form stays behind that logo menu.",
        "The generated node installer advertises CRM sidecar controls instead of the upstream CRM product name.",
        "The office stack can run one PostgreSQL server while keeping CreditSoft and CRM data in separate databases and users.",
        "CRM images stay independently updatable through the Docker profile so upstream releases can be pulled without rebuilding the intranet app."
    ],
    "download_url": "https://updates.creditsoft.app/downloads/creditsoft-office-v2026.4.28.6.zip",
    "crm_sidecar": {
        "label": "CreditSoft CRM Sidecar",
        "image": "update.creditsoft.app/creditsoft/crm-sidecar:latest",
        "update_strategy": "docker_pull",
        "source_visible_to_customer": false
    },
    "browser_companion": {
        "label": "CreditSoft Browser Companion",
        "latest_version": "2026.4.28.6",
        "download_url": "https://update.creditsoft.app/downloads/creditsoft-browser-companion-v2026.4.28.6.zip",
        "trial_days": 7,
        "trial_label": "7-day companion trial",
        "renewal_url": "https://updates.creditsoft.app/renewal/"
    },
    "intranet_client": {
        "label": "CreditSoft Employee Intranet Client",
        "latest_version": "2026.4.28.6",
        "download_url": "https://updates.creditsoft.app/downloads/creditsoft-intranet-client-installer-v2026.4.28.6.zip",
        "router_url": "http://127.0.0.1/dashboard?source=intranet-client"
    },
    "browser_companion_url": "https://update.creditsoft.app/downloads/creditsoft-browser-companion-v2026.4.28.6.zip",
    "renewal_url": "https://updates.creditsoft.app/renewal/",
    "support_url": "https://creditsoft.app/",
    "minimum_version": "2026.4.28.6",
    "update_required": true
}
