const number = (name, label, value, extra = {}) => ({ name, label, type: 'number', value, min: 0, max: 100000000, step: 0.01, ...extra });
const select = (name, label, options) => ({ name, label, type: 'select', options: options.map(o => Array.isArray(o) ? o : [o, o]) });
const text = (name, label) => ({ name, label, type: 'textarea', value: '' });
const goals = ['Lower card balances', 'Prepare for a mortgage', 'Prepare for an auto loan', 'Rent a home', 'Build a credit history', 'Plan business finances'];
const goal = () => select('goal', 'Your goal', goals);
const horizon = () => select('horizon', 'Planning window', ['30 days', '60 days', '90 days', 'Longer than 90 days']);
const issues = ['High card balances', 'Late payments', 'Unfamiliar or incorrect information', 'Collections or charge-offs', 'Short credit history', 'Recent applications'];
const issueField = () => ({ name: 'issues', label: 'Topics to review', type: 'checkboxes', options: issues });
const source = {
 budget: ['CFPB money planning toolkit', 'https://www.consumerfinance.gov/consumer-tools/educator-tools/your-money-your-goals/toolkit/'],
 debt: ['CFPB debt repayment strategies', 'https://www.consumerfinance.gov/archive/blog/how-reduce-your-debt/'],
 credit: ['CFPB guide to credit scores', 'https://www.consumerfinance.gov/consumer-tools/credit-reports-and-scores/understand-your-credit-score/'],
 scores: ['How credit scores are calculated', 'https://www.consumerfinance.gov/ask-cfpb/what-is-a-credit-score-en-315/'],
};
const cards = [number('balance','Balance',1200), number('limit','Credit limit',2000)];
const debts = [number('balance','Balance',2400), number('apr','APR (%)',20,{max:100,step:0.01}), number('minimum','Monthly minimum payment',80)];
export const tools = [
 { slug:'budget', title:'Budget coaching', category:'Everyday money', description:'See what remains after essential bills, debt payments and your savings target.', fields:[number('income','Monthly take-home income',4200),number('essential','Essential bills',2100),number('debt','Debt payments',550),number('savings','Savings target',300)], method:'Monthly cushion equals take-home income minus essential bills, debt payments and savings. Include each expense once; a positive cushion is unallocated cash, not a promise of affordability.', source:source.budget },
 { slug:'payoff', title:'Payoff planner', category:'Debt and payments', description:'Estimate the time and interest needed to pay one balance, with or without extra payments.', fields:[number('balance','Current balance',4800),number('apr','APR (%)',24.99,{max:100}),number('payment','Monthly payment',180),number('extra','Extra monthly payment',40)], method:'Assumes fixed APR, monthly interest at APR / 12, payments at month end, no fees and no new purchases. Interest is rounded to cents each month. Actual statements may use daily interest. Estimates stop at 600 months and never label an unpaid balance as paid off.', source:source.debt },
 { slug:'utilization', title:'Utilization targets', category:'Credit planning', description:'Calculate your revolving balance-to-limit ratio and the paydown needed for a chosen target.', fields:[number('limit','Total revolving credit limit',5000),number('balance','Total revolving balance',2100),number('target','Target utilization (%)',30,{max:100})], method:'Utilization is revolving balance divided by revolving credit limit. Targets are planning examples, not score cutoffs or approval requirements. A lower ratio does not imply a specific score change.', source:source.credit },
 { slug:'prep', title:'Consultation prep', category:'Planning worksheets', description:'Put your goals and questions into a worksheet you can print for your consultation.', fields:[text('goal','What do you want to accomplish?'),text('timeline','What is your time frame?'),text('balances','Which balances or payments need discussion?'),text('questions','What questions do you want answered?')], method:'Your answers become a printable worksheet. Leave out account numbers, Social Security numbers and other identifying details. Printing is optional; this page does not submit your answers or create a client record.', source:source.budget },
 { slug:'strategy', title:'Strategy planner', category:'Planning worksheets', description:'Create a review checklist around your goal, time frame and credit concerns.', fields:[goal(),horizon(),issueField()], method:'This worksheet selects general review steps from the topics you choose. It does not predict qualification, credit-score changes or dispute outcomes.', source:source.credit },
 { slug:'simulator', title:'Score scenario planner', originalTitle:'Score simulator', category:'Credit planning', description:'See utilization before and after a planned paydown. Actual credit-score changes vary.', fields:[number('limit','Total revolving credit limit',10000),number('balance','Current revolving balance',4000),number('paydown','Proposed balance paydown',1500)], method:'Compares balance-to-limit ratios before and after the paydown, keeping the limit unchanged. Actual scores depend on the full credit file and scoring model. No point estimate or score increase is claimed.', source:source.scores },
 { slug:'optimizer', title:'Utilization optimizer', category:'Credit planning', description:'Compare individual cards, overall utilization and target paydowns without double-counting balances.', fields:[number('target','Target utilization (%)',30,{max:100})], rows:{label:'Card',fields:cards}, method:'Each card contributes once to the total balance and limit. The review order uses the highest utilization first; it is not the interest-minimizing debt strategy. Use Debt comparison for APR-based planning.', source:source.credit },
 { slug:'readiness', title:'Funding readiness', category:'Credit planning', description:'Check whether you have gathered the information needed for a funding conversation.', fields:['Reviewed all relevant credit reports','Know current revolving balances and limits','Have a monthly payment budget','Checked recent payment history','Understand recent applications','Know the lender’s documentation requirements'].map((label,i)=>select(`check${i}`,label,[['unsure','Not checked yet'],['yes','Checked'],['no','Needs attention']])) , method:'Counts completed preparation checks equally. This is a document and planning checklist, not a credit score, lender model or approval decision.', source:source.credit },
 { slug:'negative', title:'Negative-item review', category:'Planning worksheets', description:'Organize report concerns and identify which information needs closer review.', fields:[number('collections','Collections to review',0,{step:1,max:100}),number('chargeoffs','Charge-offs to review',0,{step:1,max:100}),number('lates','Late-payment entries to review',0,{step:1,max:100}),select('accuracy','Have you found information that may be inaccurate?',['Not sure yet','Yes','No']),text('notes','Notes or questions (no account numbers)')], method:'Organizes the entries you identify; it does not score their severity or assert that accurate information can be removed. Check the underlying records before deciding on any dispute.', source:source.credit },
 { slug:'comparison', title:'Debt comparison', category:'Debt and payments', description:'Compare avalanche and snowball payoff plans using the same monthly budget.', fields:[number('extra','Extra monthly payment across all debts',100)], rows:{label:'Debt',fields:debts}, method:'The monthly budget is all entered minimum payments plus extra. After minimums, remaining money goes to the highest APR (avalanche) or smallest balance (snowball). Payments freed by a payoff roll to the next debt, including within the same month. Assumes fixed APRs/minimums, monthly interest, no fees or new borrowing; maximum 600 months.', source:source.debt },
 { slug:'timeline', title:'Action timeline', category:'Planning worksheets', description:'Build a practical review schedule around your goal and statement closing date.', fields:[goal(),horizon(),number('closeDay','Statement closing day',22,{min:1,max:31,step:1}),select('followup','Do you have a report or dispute follow-up pending?',['No','Yes'])], method:'Produces planning checkpoints, not legal deadlines or promised completion dates. Confirm actual statement dates with your issuer; shorter months may close on a different day.', source:source.budget },
 { slug:'recommendation', title:'Account helper', category:'Credit planning', description:'Compare questions to ask about account types, costs and reporting before applying.', fields:[select('category','Account type to explore',['Secured credit card','Credit-builder loan','Unsecured credit card','Business account']),select('priority','Main question',['Fees and total cost','Credit reporting','Deposit or collateral','Payment affordability'])], method:'Displays a comparison checklist for the category you select. It does not rank specific providers, recommend an application or assess approval eligibility.', source:source.budget },
];
export const sourceLink = 'https://credit-essense.com/tools/';
