<?php

return [
    'config_path' => base_path('creditsoft'),
    'portal_url' => env('CREDITSOFT_PORTAL_URL', 'https://www.creditsoft.app'),
    'mail' => [
        'enabled' => filter_var(env('CREDITSOFT_MAIL_ENABLED', false), FILTER_VALIDATE_BOOL, FILTER_NULL_ON_FAILURE) ?? false,
        'provider' => env('CREDITSOFT_MAIL_PROVIDER', 'custom_smtp'),
        'provider_settings' => env('CREDITSOFT_MAIL_PROVIDER_SETTINGS', ''),
        'local_relay' => filter_var(env('CREDITSOFT_MAIL_LOCAL_RELAY', false), FILTER_VALIDATE_BOOL, FILTER_NULL_ON_FAILURE) ?? false,
    ],
    'lead_capture' => [
        'turnstile_site_key' => env('CREDITSOFT_TURNSTILE_SITE_KEY', env('TURNSTILE_SITE_KEY', '')),
        'turnstile_secret' => env('CREDITSOFT_TURNSTILE_SECRET_KEY', env('TURNSTILE_SECRET_KEY', '')),
        'require_turnstile' => filter_var(env('CREDITSOFT_LEAD_CAPTURE_REQUIRE_TURNSTILE', false), FILTER_VALIDATE_BOOL, FILTER_NULL_ON_FAILURE) ?? false,
        'require_mx' => filter_var(env('CREDITSOFT_LEAD_CAPTURE_REQUIRE_MX', true), FILTER_VALIDATE_BOOL, FILTER_NULL_ON_FAILURE) ?? true,
    ],
    'audit' => [
        'retention_days' => (int) env('CREDITSOFT_AUDIT_RETENTION_DAYS', 30),
        'minimum_retention_days' => (int) env('CREDITSOFT_AUDIT_MINIMUM_RETENTION_DAYS', 7),
        'maximum_retention_days' => (int) env('CREDITSOFT_AUDIT_MAXIMUM_RETENTION_DAYS', 45),
        'disk_free_warning_gb' => (float) env('CREDITSOFT_AUDIT_DISK_FREE_WARNING_GB', 50),
        'disk_free_critical_gb' => (float) env('CREDITSOFT_AUDIT_DISK_FREE_CRITICAL_GB', 20),
        'disk_percent_warning' => (float) env('CREDITSOFT_AUDIT_DISK_PERCENT_WARNING', 20),
        'disk_percent_critical' => (float) env('CREDITSOFT_AUDIT_DISK_PERCENT_CRITICAL', 10),
    ],
    'diagnostics' => [
        'host_snapshot_path' => env('CREDITSOFT_HOST_DIAGNOSTICS_PATH', storage_path('app/private/host-diagnostics.json')),
        'host_snapshot_max_age_seconds' => (int) env('CREDITSOFT_HOST_DIAGNOSTICS_MAX_AGE_SECONDS', 900),
        'cluster_probe_bytes' => (int) env('CREDITSOFT_CLUSTER_PROBE_BYTES', 64 * 1024 * 1024),
        'public_speed_path' => env('CREDITSOFT_PUBLIC_SPEED_PATH', storage_path('app/private/public-internet-speed.json')),
    ],
    'cluster' => [
        'restore_incoming_backups' => filter_var(env('CREDITSOFT_CLUSTER_RESTORE_INCOMING_BACKUPS', false), FILTER_VALIDATE_BOOL, FILTER_NULL_ON_FAILURE) ?? false,
        'restore_marker_path' => env('CREDITSOFT_CLUSTER_RESTORE_MARKER_PATH') ?: storage_path('app/private/database-backups/cluster-restore-state.json'),
        'scheduled_database_backups' => filter_var(env('CREDITSOFT_DATABASE_BACKUPS_SCHEDULED', true), FILTER_VALIDATE_BOOL, FILTER_NULL_ON_FAILURE) ?? true,
    ],
    'ui' => [
        'review_label_style' => env('CREDITSOFT_REVIEW_LABEL_STYLE', '10'),
        'review_label_styles' => [
            [
                'key' => '1',
                'number' => 1,
                'label' => 'Rail bar',
                'description' => 'Thin rail with icon + label text.',
            ],
            [
                'key' => '2',
                'number' => 2,
                'label' => 'Stamped mark',
                'description' => 'Compact compliance-stamp treatment.',
                'recommended' => true,
            ],
            [
                'key' => '3',
                'number' => 3,
                'label' => 'Bracket rail',
                'description' => 'Hard-edged bracket label with icon.',
            ],
            [
                'key' => '4',
                'number' => 4,
                'label' => 'Corner fold',
                'description' => 'Small folded-corner review label.',
                'recommended' => true,
            ],
            [
                'key' => '5',
                'number' => 5,
                'label' => 'Ticket edge',
                'description' => 'Ticket-like label with angled edge.',
            ],
            [
                'key' => '6',
                'number' => 6,
                'label' => 'Review strip',
                'description' => 'Striped review tape style.',
            ],
            [
                'key' => '7',
                'number' => 7,
                'label' => 'Evidence tag',
                'description' => 'Attached evidence-tag look.',
                'recommended' => true,
            ],
            [
                'key' => '8',
                'number' => 8,
                'label' => 'Minimal underline',
                'description' => 'Quiet text label with underline.',
            ],
            [
                'key' => '9',
                'number' => 9,
                'label' => 'Code plate',
                'description' => 'Tight coded plate with stronger structure.',
            ],
            [
                'key' => '10',
                'number' => 10,
                'label' => 'Production rail',
                'description' => 'Best production bridge from the gallery work.',
                'recommended' => true,
            ],
            [
                'key' => '11',
                'number' => 11,
                'label' => 'File tab',
                'description' => 'Small tab label for report reviews.',
            ],
            [
                'key' => '12',
                'number' => 12,
                'label' => 'Mixed marker',
                'description' => 'Hybrid style with a little more character.',
            ],
        ],
    ],
    'tailscale_hostname' => env('CREDITSOFT_TAILSCALE_HOSTNAME', 'creditsoft-intranet'),
    'access' => [
        'roles' => [
            'owner_admin' => [
                'label' => 'Owner admin',
                'description' => 'Full office control across the intranet, settings, billing, and ops.',
                'workspace' => true,
                'ops' => true,
                'readonly' => false,
                'areas' => ['All workspace lanes', 'Users + roles', 'Connectivity + backup', 'Social / Meta', 'Growth data', 'Ops panel'],
            ],
            'admin' => [
                'label' => 'Admin',
                'description' => 'Runs daily operations with write access across office settings and client work.',
                'workspace' => true,
                'ops' => true,
                'readonly' => false,
                'areas' => ['Workspace lanes', 'Users + roles', 'Connectivity + backup', 'Social / Meta', 'Growth data', 'Ops panel'],
            ],
            'manager' => [
                'label' => 'Manager',
                'description' => 'Oversees direct reports, client queues, and office follow-up without owning the full admin lane.',
                'workspace' => true,
                'ops' => false,
                'readonly' => false,
                'areas' => ['Team oversight', 'Clients', 'Inbox', 'Tasks', 'Social / Meta', 'Growth data'],
            ],
            'demo_admin' => [
                'label' => 'Demo admin',
                'description' => 'Sees the full office setup without changing records.',
                'workspace' => true,
                'ops' => true,
                'readonly' => true,
                'areas' => ['Workspace lanes', 'Users + roles', 'Connectivity + backup', 'Social / Meta', 'Growth data', 'Ops panel'],
            ],
            'case_manager' => [
                'label' => 'Case manager',
                'description' => 'Owns client dossiers, dispute flow, follow-up, and day-to-day casework.',
                'workspace' => true,
                'ops' => false,
                'readonly' => false,
                'areas' => ['Clients', 'Inbox', 'Tasks', 'Notes', 'Letters', 'Briefs'],
            ],
            'staff' => [
                'label' => 'Staff',
                'description' => 'Handles intake, tasks, notes, and normal office workflows.',
                'workspace' => true,
                'ops' => false,
                'readonly' => false,
                'areas' => ['Clients', 'Inbox', 'Tasks', 'Notes'],
            ],
            'demo_staff' => [
                'label' => 'Demo staff',
                'description' => 'Read-only staff view for walkthroughs, training, and demos.',
                'workspace' => true,
                'ops' => false,
                'readonly' => true,
                'areas' => ['Clients', 'Inbox', 'Tasks', 'Notes'],
            ],
            'social_media_manager' => [
                'label' => 'Social media manager',
                'description' => 'Owns the Meta lane, content calendar, publishing, paid social setup, WhatsApp follow-up, and Growth data.',
                'workspace' => true,
                'ops' => false,
                'readonly' => false,
                'areas' => ['Social / Meta', 'Content calendar', 'Publishing', 'Lead ads', 'WhatsApp follow-up', 'Growth data'],
            ],
            'ai-operator' => [
                'label' => 'AI operator',
                'description' => 'Focuses on drafting, prompts, AI-assisted workflows, and support content.',
                'workspace' => true,
                'ops' => false,
                'readonly' => false,
                'areas' => ['AI lanes', 'Briefs', 'Notes', 'Social drafting'],
            ],
        ],
        'login_accounts' => [
            [
                'role' => 'owner_admin',
                'label' => 'Owner admin',
                'name' => 'Matthew Murphy',
                'email' => 'mmurphy@creditsoft.app',
                'password' => 'password',
                'readonly' => false,
                'description' => 'Full system control, ops panel, and config authority.',
            ],
            [
                'role' => 'admin',
                'label' => 'Admin',
                'name' => 'Office Admin',
                'email' => 'admin@example.com',
                'password' => 'password',
                'readonly' => false,
                'description' => 'Daily operations and oversight with write access.',
            ],
            [
                'role' => 'demo_admin',
                'label' => 'Demo admin',
                'name' => 'Demo Admin',
                'email' => 'demo.admin@example.com',
                'password' => 'password',
                'readonly' => true,
                'description' => 'View everything, including ops, without changing records.',
            ],
            [
                'role' => 'case_manager',
                'label' => 'Case manager',
                'name' => 'Case Manager',
                'email' => 'case.manager@example.com',
                'password' => 'password',
                'readonly' => false,
                'description' => 'Owns client dossiers, disputes, and follow-up workflows.',
            ],
            [
                'role' => 'staff',
                'label' => 'Staff',
                'name' => 'Workflow Staff',
                'email' => 'staff@example.com',
                'password' => 'password',
                'readonly' => false,
                'description' => 'Handles intake, notes, tasks, and normal casework.',
            ],
            [
                'role' => 'demo_staff',
                'label' => 'Demo staff',
                'name' => 'Demo Staff',
                'email' => 'demo.staff@example.com',
                'password' => 'password',
                'readonly' => true,
                'description' => 'Read-only operator view for walkthroughs and training.',
            ],
        ],
    ],
    'migration_operator' => [
        'capture_types' => [
            'letter_library',
            'letter_detail',
            'client_dashboard',
            'billing',
            'batch_print',
            'score_history',
            'generic',
        ],
        'allowed_hosts' => [
            'app.disputefox.com',
            'www.disputefox.com',
            'disputefox.com',
            'pulse.disputeprocess.com',
            'disputeprocess.com',
            'www.disputeprocess.com',
            'app.creditrepaircloud.com',
            'www.creditrepaircloud.com',
            'creditrepaircloud.com',
            'app.clientdisputemanager.com',
            'www.clientdisputemanager.com',
            'clientdisputemanager.com',
            'identityiq.com',
            'www.identityiq.com',
            'member.identityiq.com',
            'smartcredit.com',
            'www.smartcredit.com',
            'member.smartcredit.com',
            'myscoreiq.com',
            'www.myscoreiq.com',
        ],
    ],
    'client_providers' => [
        'catalog' => [
            [
                'key' => 'smartcredit',
                'label' => 'SmartCredit',
                'description' => '3-bureau reports, score tracker, and archive imports.',
                'companion_start_url' => 'https://www.smartcredit.com/member/credit-report/smart-3b/',
                'companion_logout_url' => 'https://www.smartcredit.com/logout',
            ],
            [
                'key' => 'identityiq',
                'label' => 'IdentityIQ',
                'description' => 'IdentityIQ bureau pulls, alerts, and login with a saved security-answer step.',
                'companion_start_url' => 'https://member.identityiq.com/Dashboard.aspx',
            ],
            [
                'key' => 'experian',
                'label' => 'Experian',
                'description' => 'Direct Experian account or bureau portal.',
                'companion_start_url' => 'https://www.experian.com/',
            ],
            [
                'key' => 'equifax',
                'label' => 'Equifax',
                'description' => 'Direct Equifax account or bureau portal.',
                'companion_start_url' => 'https://www.equifax.com/',
            ],
            [
                'key' => 'transunion',
                'label' => 'TransUnion',
                'description' => 'Direct TransUnion account or bureau portal.',
                'companion_start_url' => 'https://www.transunion.com/',
            ],
            [
                'key' => 'myscoreiq',
                'label' => 'MyScoreIQ',
                'description' => 'MyScoreIQ monitoring or archive imports.',
                'companion_start_url' => 'https://www.myscoreiq.com/',
            ],
            [
                'key' => 'credit_karma',
                'label' => 'Credit Karma',
                'description' => 'Credit Karma score and account tracking.',
                'companion_start_url' => 'https://www.creditkarma.com/credit-health/transunion/credit-report',
            ],
            [
                'key' => 'custom',
                'label' => 'Custom provider',
                'description' => 'Use when the source is not in the standard list yet.',
            ],
        ],
        'statuses' => [
            ['key' => 'connected', 'label' => 'Connected'],
            ['key' => 'import_only', 'label' => 'Import only'],
            ['key' => 'needs_client_payment', 'label' => 'Needs client payment'],
            ['key' => 'needs_reactivation', 'label' => 'Needs reactivation'],
            ['key' => 'needs_credentials', 'label' => 'Needs credentials'],
            ['key' => 'paused', 'label' => 'Paused'],
            ['key' => 'disconnected', 'label' => 'Disconnected'],
        ],
    ],
    'tunnels' => [
        'tailscale' => [
            'required' => filter_var(env('CREDITSOFT_TAILSCALE_REQUIRED', true), FILTER_VALIDATE_BOOL, FILTER_NULL_ON_FAILURE) ?? true,
            'hostname' => env('CREDITSOFT_TAILSCALE_HOSTNAME', 'creditsoft-intranet'),
            'tailnet' => env('CREDITSOFT_TAILSCALE_TAILNET', ''),
            'api_key' => env('CREDITSOFT_TAILSCALE_API_KEY') ?: env('CREDITSOFT_TAILSCALE_API_AUTHTOKEN'),
            'api_authtoken' => env('CREDITSOFT_TAILSCALE_API_AUTHTOKEN'),
            'api_key_expires_at' => env('CREDITSOFT_TAILSCALE_API_KEY_EXPIRES_AT', ''),
            'api_key_warning_days' => (int) env('CREDITSOFT_TAILSCALE_API_KEY_WARNING_DAYS', 3),
        ],
        'ngrok' => [
            'enabled' => filter_var(env('CREDITSOFT_NGROK_ENABLED', false), FILTER_VALIDATE_BOOL, FILTER_NULL_ON_FAILURE) ?? false,
            'api_only' => filter_var(env('CREDITSOFT_NGROK_API_ONLY', true), FILTER_VALIDATE_BOOL, FILTER_NULL_ON_FAILURE) ?? true,
            'authtoken' => env('CREDITSOFT_NGROK_AUTHTOKEN'),
            'api_key' => env('CREDITSOFT_NGROK_API_KEY'),
            'domain' => env('CREDITSOFT_NGROK_DOMAIN', ''),
            'config_path' => env('CREDITSOFT_NGROK_CONFIG_PATH', ''),
        ],
    ],
    'cluster_ssh' => [
        'enabled' => filter_var(env('CREDITSOFT_CLUSTER_SSH_ENABLED', true), FILTER_VALIDATE_BOOL, FILTER_NULL_ON_FAILURE) ?? true,
        'identity_file' => env('CREDITSOFT_CLUSTER_SSH_IDENTITY_FILE', 'creditsoft_cluster_ed25519'),
        'comment_prefix' => env('CREDITSOFT_CLUSTER_SSH_COMMENT_PREFIX', 'creditsoft@cluster'),
        'source_cidrs' => env('CREDITSOFT_CLUSTER_SSH_SOURCE_CIDRS', '100.64.0.0/10,fd7a:115c:a1e0::/48'),
    ],
    'api' => [
        'enabled' => filter_var(env('CREDITSOFT_API_ENABLED', true), FILTER_VALIDATE_BOOL, FILTER_NULL_ON_FAILURE) ?? true,
        'token' => env('CREDITSOFT_API_TOKEN'),
        'public_base_url' => env('CREDITSOFT_API_PUBLIC_BASE_URL', ''),
        'docs_path' => env('CREDITSOFT_API_DOCS_PATH', base_path('creditsoft/openapi.yaml')),
        'docs_hosts' => array_values(array_filter(array_map(
            static fn (string $host): string => trim($host),
            explode(',', (string) env('CREDITSOFT_API_DOCS_HOSTS', 'api.creditsoft.app,api.creditsoft.com'))
        ))),
        'docs_host_prefixes' => array_values(array_filter(array_map(
            static fn (string $prefix): string => trim($prefix),
            explode(',', (string) env('CREDITSOFT_API_DOCS_HOST_PREFIXES', 'api.'))
        ))),
        'docs_host_labels' => [
            'api.creditsoft.app' => 'CreditSoft',
            'api.creditsoft.com' => 'CreditSoft',
            'api.net30hosting.com' => 'Net30Hosting',
        ],
        'browser_companion' => [
            'claim_ttl_minutes' => (int) env('CREDITSOFT_BROWSER_COMPANION_CLAIM_TTL_MINUTES', 20),
            'default_import_interval_hours' => (int) env('CREDITSOFT_BROWSER_COMPANION_DEFAULT_IMPORT_INTERVAL_HOURS', 168),
            'minimum_import_interval_hours' => (int) env('CREDITSOFT_BROWSER_COMPANION_MIN_IMPORT_INTERVAL_HOURS', 24),
            'maximum_import_interval_hours' => (int) env('CREDITSOFT_BROWSER_COMPANION_MAX_IMPORT_INTERVAL_HOURS', 720),
        ],
    ],
    'integrations' => [
        'crm' => [
            'enabled' => filter_var(env('CREDITSOFT_CRM_ENABLED', false), FILTER_VALIDATE_BOOL, FILTER_NULL_ON_FAILURE) ?? false,
            'base_url' => env('CREDITSOFT_CRM_BASE_URL', ''),
            'api_key' => env('CREDITSOFT_CRM_API_KEY', ''),
            'image' => env('CRM_IMAGE', 'creditsoft/crm-sidecar:local'),
            'base_image' => env('CRM_BASE_IMAGE', 'update.creditsoft.app/creditsoft/crm-sidecar:latest'),
            'database' => [
                'host' => env('CRM_PG_HOST', env('DB_HOST', '127.0.0.1')),
                'port' => env('CRM_PG_PORT', env('DB_PORT', 5432)),
                'database' => env('CRM_PG_DATABASE', 'crm'),
                'username' => env('CRM_PG_USER', 'crm'),
                'password' => env('CRM_PG_PASSWORD', ''),
            ],
        ],
    ],
    'licensing' => [
        'features' => [
            'workspace' => [
                'label' => 'Workspace access',
            ],
            'partner_api' => [
                'label' => 'Office API',
            ],
            'browser_companion' => [
                'label' => 'Browser companion',
            ],
        ],
        'feature_trials' => [
            'browser_companion' => [
                'days' => (int) env('CREDITSOFT_BROWSER_COMPANION_TRIAL_DAYS', 7),
                'label' => 'Browser companion trial',
                'upgrade_message' => 'The one-week Browser companion trial has ended. Upgrade to Enterprise Pro to keep pulling provider reports, importing legacy CRM data, and using companion automations.',
            ],
        ],
        'default_features' => [
            'workspace' => true,
            'partner_api' => true,
            'browser_companion' => true,
        ],
        'plans' => [
            'enterprise' => [
                'label' => 'Enterprise',
                'features' => [
                    'workspace' => true,
                    'partner_api' => true,
                    'browser_companion' => false,
                ],
            ],
            'enterprise_pro' => [
                'label' => 'Enterprise Pro',
                'features' => [
                    'workspace' => true,
                    'partner_api' => true,
                    'browser_companion' => true,
                ],
            ],
        ],
        'plan_aliases' => [
            'enterprise' => 'enterprise',
            'enterprise-basic' => 'enterprise',
            'enterprise_basic' => 'enterprise',
            'packaged' => 'enterprise',
            'packaged-enterprise' => 'enterprise',
            'packaged_enterprise' => 'enterprise',
            'enterprise-pro' => 'enterprise_pro',
            'enterprise_pro' => 'enterprise_pro',
            'enterprise pro' => 'enterprise_pro',
            'pro' => 'enterprise_pro',
            'api' => 'enterprise_pro',
            'api-version' => 'enterprise_pro',
            'api_version' => 'enterprise_pro',
            'packaged-pro' => 'enterprise_pro',
            'packaged_pro' => 'enterprise_pro',
        ],
        'renewal' => [
            'payee_name' => env('CREDITSOFT_LICENSE_RENEWAL_PAYEE', 'Matthew Murphy'),
            'zelle_contact' => env('CREDITSOFT_LICENSE_RENEWAL_ZELLE', 'z@creditsoft.app'),
            'bank_name' => env('CREDITSOFT_LICENSE_RENEWAL_BANK', 'Chase'),
            'expected_subject' => env('CREDITSOFT_LICENSE_RENEWAL_EXPECTED_SUBJECT', 'You received money with Zelle®'),
            'dedicated_mailbox_note' => env('CREDITSOFT_LICENSE_RENEWAL_MAILBOX_NOTE', 'Use a dedicated inbox for Zelle/Chase payment notices only. Do not route Supabase, support, app alerts, or general office mail into this mailbox.'),
            'zelle_address_note' => env('CREDITSOFT_LICENSE_RENEWAL_ADDRESS_NOTE', 'Some banks/Zelle reject addresses like zelle@yourdomain.com. Use the bank-approved Zelle email shown on the QR, such as z@creditsoft.app or another dedicated address the bank accepts.'),
            'memo_prefix' => env('CREDITSOFT_LICENSE_RENEWAL_MEMO_PREFIX', 'CreditSoft renewal'),
            'default_amount' => env('CREDITSOFT_LICENSE_RENEWAL_AMOUNT'),
            'payment_note' => env('CREDITSOFT_LICENSE_RENEWAL_PAYMENT_NOTE', 'Payments can take up to 8 hours to process.'),
            'support_email' => env('CREDITSOFT_LICENSE_RENEWAL_SUPPORT_EMAIL', 'hello@creditsoft.app'),
            'support_phone' => env('CREDITSOFT_LICENSE_RENEWAL_SUPPORT_PHONE', ''),
            'qr_image_path' => env('CREDITSOFT_LICENSE_RENEWAL_QR_IMAGE', '/assets/payments/zelle.png'),
            'qr_text' => env('CREDITSOFT_LICENSE_RENEWAL_QR_TEXT', ''),
        ],
    ],
    'required_files' => [
        'config.yaml',
        'agents.yaml',
        'crew.yaml',
        'tools.yaml',
        'persona.yaml',
        'soul.yaml',
        'tasks.yaml',
        'ai_models.yaml',
        'letter_templates.yaml',
        'roadmap.json',
        'violation_rules.yaml',
    ],
    'signal_allowlist' => [
        'client_cuid',
        'event_type',
        'stage',
        'recorded_at',
        'brief_title',
        'brief_excerpt',
        'metric_key',
        'metric_value',
        'categories',
        'summary',
        'provider_key',
        'workflow_key',
        'source',
        'bureau',
        'counts',
        'flags',
        'timing',
    ],
    'report_feedback_allowlist' => [
        'installation_id',
        'org_scoped_person_id',
        'event_type',
        'recorded_at',
        'provider_key',
        'provider_profile',
        'source_type',
        'cycle_label',
        'client_stage',
        'business_timing',
        'score_snapshot',
        'report_snapshot',
        'bureau_coverage',
        'provider_warnings',
        'metro2_snapshot',
        'graph_kind',
    ],
    'signal_denylist_patterns' => [
        '/\b\d{3}-\d{2}-\d{4}\b/',
        '/\b\d{9}\b/',
        '/\b(?:\+?1[-.\s]?)?(?:\(?\d{3}\)?[-.\s]?)?\d{3}[-.\s]?\d{4}\b/',
        '/[A-Z0-9._%+\-]+@[A-Z0-9.\-]+\.[A-Z]{2,}/i',
    ],
    'installer' => [
        'enabled' => env('CREDITSOFT_INSTALLER_ENABLED', true),
        'state_path' => env('CREDITSOFT_INSTALLER_STATE_PATH', storage_path('app/private/install/state.json')),
        'ad_feed_path' => env('CREDITSOFT_AD_FEED_PATH', base_path('creditsoft/install_ads.json')),
        'ad_feed_url' => env('CREDITSOFT_AD_FEED_URL', 'https://www.creditsoft.app/api/install-ads'),
        'billing_intelligence_enabled' => filter_var(env('CREDITSOFT_BILLING_INTELLIGENCE_ENABLED', true), FILTER_VALIDATE_BOOL, FILTER_NULL_ON_FAILURE) ?? true,
        'billing_intelligence_url' => env('CREDITSOFT_BILLING_INTELLIGENCE_URL', 'https://www.creditsoft.app/api/license-billing-intelligence'),
        'logo_path' => env('CREDITSOFT_INSTALLER_LOGO_PATH', public_path('installer/branding')),
        'logo_url_prefix' => env('CREDITSOFT_INSTALLER_LOGO_URL_PREFIX', '/installer/branding'),
        'license_mode' => env('CREDITSOFT_LICENSE_MODE', 'auto'),
        'license_check_url' => env('CREDITSOFT_LICENSE_URL'),
        'license_check_api_url' => env('CREDITSOFT_LICENSE_API_URL', 'https://api.creditsoft.app/license/validate'),
        'license_check_portal_url' => env('CREDITSOFT_LICENSE_PORTAL_URL', 'https://www.creditsoft.app/license/validate.json'),
        'license_grace_days' => (int) env('CREDITSOFT_LICENSE_GRACE_DAYS', 7),
        'verification_window_days' => (int) env('CREDITSOFT_LICENSE_VERIFICATION_WINDOW_DAYS', 7),
    ],
    'updates' => [
        'current_version' => env('CREDITSOFT_APP_VERSION', '0.9.1'),
        'current_build' => env('CREDITSOFT_APP_BUILD', env('CREDITSOFT_APP_VERSION', '0.9.1')),
        'channel' => env('CREDITSOFT_UPDATE_CHANNEL', 'stable'),
        'feed_url' => env('CREDITSOFT_UPDATE_FEED_URL', 'https://updates.creditsoft.app/api/update-feed'),
        'fallback_feed_url' => env('CREDITSOFT_UPDATE_FEED_FALLBACK_URL', ''),
        'cache_minutes' => (int) env('CREDITSOFT_UPDATE_FEED_CACHE_MINUTES', 15),
        'browser_companion_download_url' => env('CREDITSOFT_BROWSER_COMPANION_DOWNLOAD_URL', ''),
        'intranet_client_download_url' => env('CREDITSOFT_INTRANET_CLIENT_DOWNLOAD_URL', ''),
    ],
    'browser_capture_path' => env('CREDITSOFT_BROWSER_CAPTURE_PATH', storage_path('app/private/browser-captures')),
    'document_path' => env('CREDITSOFT_DOCUMENT_PATH', storage_path('app/private/client-documents')),
    'ai' => [
        'providers' => [
            'opencode_zen' => [
                'driver' => 'openai-compatible',
                'key' => env('OPENCODE_API_KEY'),
                'url' => env('OPENCODE_BASE_URL', 'https://opencode.ai/zen/v1/chat/completions'),
                'models' => [
                    'text' => [
                        'default' => env('OPENCODE_TEXT_MODEL', 'big-pickle'),
                        'cheapest' => env('OPENCODE_CHEAPEST_MODEL', 'big-pickle'),
                        'smartest' => env('OPENCODE_SMARTEST_MODEL', 'big-pickle'),
                    ],
                ],
            ],
            'ollama_cloud' => [
                'driver' => 'ollama',
                'key' => env('OLLAMA_CLOUD_API_KEY'),
                'url' => 'https://ollama.com',
                'models' => [
                    'text' => [
                        'default' => env('OLLAMA_CLOUD_TEXT_MODEL', 'nemotron-3-super:cloud'),
                        'cheapest' => env('OLLAMA_CLOUD_CHEAPEST_MODEL', 'nemotron-mini'),
                        'smartest' => env('OLLAMA_CLOUD_SMARTEST_MODEL', 'nemotron-3-super:cloud'),
                    ],
                ],
            ],
        ],
    ],
];
